# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
os: windows
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту maximrybetsky@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -maximrybetsky@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="f20152d5-aa1c-419c-a23a-20d0784729cf"